# site settings
title: Develop Team_SCV
subtitle: Team_SCV
email:  <b>[L.jaewoo]</b>leemjw87@naver.com<br>
        <b>[S.yusu]</b>sys@naver.com<br>
        <b>[Y.sagnho]</b>riose2927@gmail.com<br>
        <b>[P.Jeongkweon]</b>pjk280230@gmail.com<br>
        <b>[K.Hyunwook]</b>thy1348@gmail.com</br>
        
description: A responsive site template designed by Developer Yun SangHo<br /> and released under the Creative Commons.
baseurl:
url: 
author:
street_address: Deajun Munjung street 33, 
city: Tan-bank
state: Riviera Suit
zip_code: The Sceond place
country: Republic of Korea
phone: <b>[L.jaewoo]</b>010.6247.3940<br>
       <b>[S.yusu]</b>010.9936.1451<br>
       <b>[Y.sagnho]</b>010.4496.2415<br>
       <b>[P.Jeongkweon]</b>010.4433.2289</br>
       <b>[K.Hyunwook]</b>010.3907.8112</br>

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
